//
//  MyAccountConstant.swift
//  GoJekProvider
//
//  Created by apple on 28/02/19.
//  Copyright © 2019 Appoets. All rights reserved.
//

import UIKit

enum MyAccountConstant {
    
    //MARK: - String
    static let yourRefferalcode = "Your Referral Code"
    static let referralCount = "Referral Count"
    static let referralAmount = "Referral Amount"
    static let account = "My Account"
    static let profile = "Profile"
    static let manageAddress = "Manage Address"
    static let payment = "Payment"
    static let transaction = "Transaction"
    static let inviteReferral = "Invite Referrals"
    static let privacyPolicy = "Privacy Policy"
    static let pdfViewer = "Pdf Viewer"
    static let manageService = "Manage Services"
    static let manageDocument = "Manage Documents"
    static let Language = "Language"
    static let support = "Support"
    static let call = "Call"
    static let mail = "Mail"
    static let editInformation = "If you change any filed's you can ride only when admin is approved"
    static let Edit = "Edit"
    static let website = "Website"
    static let contactOurTeam = "Contact Our Team Via"
    static let supportDesc = "You can contact our team \n\n anytime for your queries."
    static let changePassword = "Change Password ?"
    static let changePwd = "Change Password"
    static let hundred = "$100"
    static let fiveHundred = "$500"
    static let thousand = "$1000"
    static let createNewPassword = "Create new password"
    static let resetPassword = "Reset Password"
    static let otpVerification = "OTP Verification"
    static let invalidOtp = "Invalid OTP"
    static let enterOtp = "Enter OTP"
    static let logoutMsg = "Are you sure want to logout?"
    static let logout = "Logout"
    static let upload = "Upload"
    static let selectLanguage = "Select Language"
    static let save = "Save"
    static let language = "Language"
    static let plus = "+"
    static let inviteContent = "Hey, I am using  \(APPConstant.appName) and invite you to join! Use my Referral code: "
    static let haveGoodDay = "Have a good day!"
    static let inviteFriend = "Invite your friends and earn"
    static let forEvery = "for every"
    static let newUser = "new users"
    static let cancel = "Cancel"
    static let ok = "Ok"
    static let submit = "Submit"
    static let loginManual = "MANUAL"
    static let transportTitle = "I am ready to Drive"
    static let orderTitle = "I am ready to Deliver"
    static let serviceTitle = "I am ready to Serve"
    static let courierDelivery = "I am ready to Courier"
    static let transportDescription = "Setup your Vehicle"
    static let orderDescription = "Setup your Deliveries"
    static let serviceDescription = "Setup your Services"
    static let courierDescription = "Setup your Deliveries"
    static let carCategory = "Car Category"
    static let vehicleModel = "Vehicle Model"
    static let vehicleYear = "Vehicle Year"
    static let vehicleColor = "Vehicle Color"
    static let vehicleLicensePlate = "Vehicle License Plate"
    static let vehicleMake = "Vehicle Make"
    static let documentUpload = "Document Upload"
    static let rcBook = "RC Book"
    static let Insurance = "Insurance"
    static let vehicleName = "Vehicle Name"
    static let AddVehicle = "Add Vehicle"
    static let rate = "Rate:"
    static let uploadFrontPage = "Upload Front Page"
    static let uploadBackPage = "Upload Back Page"
    static let expiryDate = "Please select Expiry Date"
    static let validExpiryDate = "Please select valid Expiry Date"
    static let wheelChair = "Wheel Chair"
    static let childSeat = "Child Seat"

    static let frontImage = "Please Upload Front Image"
    static let backImage = "Please Upload Back Image"
    static let EmptyDoucment = "No Document available"
    static let EmptyService = "No Service available"

    static let addBaseFare = "Please Add base fare"
    static let languageSuccess = "Language updated successfully"
    static let bankDetails = "Bank details"
    static let Earning = "Earnings"
    static let bankDetailsEmpty = "No Bank details"
    static let next = "Next"
    static let showVehicle = "Show my vehicles"
    static let showDelivery = "Show my Deliveries"
    static let showService = "Show my Services"
    static let addVechile = "Add Vehicle Successfully"
    static let editVechile = "Edit Vehicle Successfully"
    static let emptyService = "No Service Found"
    static let today = "Today"
    static let thisWeek = "This week"
    static let thisMonth = "This month"
    static let frontPdf = "Please Upload Front Pdf"
    static let backPdf = "Please Upload Back Pdf"
    static let view = "view"
    static let front = " (Front)"
    static let back = " (Back)"
    static let todayTask = "Today's Completed Target"
    static let weekTask = "This week Target"
    static let monthTask = "This month Target"
    static let VvehicleName = "Please Enter the Vehicle Name"
    static let VvehicleLicensePlate = "Please Enter the Vehicle License Plate"
    static let VcarCategory = "Please Enter the Car Category"
    static let VvehicleModel = "Please Enter the Vehicle Model"
    static let VvehicleYear = "Please Enter the Vehicle Year"
    static let VvehicleColor = "Please Enter the Vehicle Color"
    static let VvehicleMake = "Please Enter the Vehicle Make"
    static let availablePayment = "Available Payments"
    static let expiry = "Expiry"
    static let expiryPlaceholder = "dd-mm-yyyy"
    static let myQRcode = "My QRCode"
    static let scanQRCode = "Scan QRCode"
    static let qrCodeTitle = "Scan for send or receive amount"
    static let qrCodeSendAmount = "Send Amount"
    static let qrCodeReceiveAmount = "Receive Amount"
    static let common = "COMMON"
    static let waitingApproval = "Waiting for approval"

    //Payment
    static let savedCard = "Saved Card"
    static let saveCardDescription = "Card for receiving the customer payment"
    static let wallet = "Wallet"
    static let enterAmount = "Enter Amount"
    static let addAmount = "Add Amount"
    static let oldPassword = "Old Password"
    static let newPassword = "New Password"
    static let confirmPassword = "Confirm Password"
    static let Otp = "Otp"
    static let addCard = "Add Card Payments"
    static let noPaymentType = "No Payment gateway"
    static let choosePayment = "Choose Payment"

    
    //wallet Post
    static let amount = "amount"
    static let card_id = "card_id"
    static let user_type = "user_type"
    static let payment_Mode = "payment_mode"
    
    //Message
    static let updateSuccess = "Updated Successfully"
    static let vehicleImageUpload = "please upload Vehicle Image"
    static let rcBookImageUpload = "please upload RC Book Image"
    static let InsuranceImageUpload = "please upload Insurance Image"
    static let addCardAlert = "Please add card "
    static let cardSelection = "Please select card"
    static let cardEmptyField = "Please add valid amount"
    static let cardNumberEmpty = "Please enter card number"
    static let monthEmpty = "Please enter month"
    static let ccvEmpty = "Please enter cvv number"
    static let yearEmpty = "Please enter year"
    static let noTransaction = "No Transaction"
    static let bankSucess = "Bank Details Updated sucessfully"
    static let AddAmountSuccess = "Amount Added Successfully"
    static let validAmount = "Enter amount more than 0 and proceed"


    
    //Manage address
    static let savedLocation = "Saved Locations"
    static let edit = "Edit"
    static let delete = "Delete"
    static let addNewAddress = "Add New Address"
    static let transactionId = "Transaction Id"
    static let status = "Status"
    static let transactionID = "Transaction id"
    static let date = "Date"
    
    //MARK: - XIB
    static let AccountCollectionViewCell = "AccountCollectionViewCell"
    static let SavedAddressCell = "SavedAddressCell"
    static let ManageServiceTableViewCell = "ManageServiceTableViewCell"
    static let ManageDocumentTableViewCell = "ManageDocumentTableViewCell"
    static let DocumentTableViewCell = "DocumentTableViewCell"
    static let SetupVehicleTableViewCell = "SetupVehicleTableViewCell"
    static let SetupServiceTableViewCell = "SetupServiceTableViewCell"
    static let LanguageTableViewCell = "LanguageTableViewCell"
    static let PaymentTypeCell = "PaymentTypeCell"
    static let PaymentCardCell = "PaymentCardCell"
    static let paymentView = "PaymentView"
    static let TransactionTableCell = "TransactionTableCell"
    static let TransactionHeaderView = "TransactionHeaderView"
    static let BankDetailCell = "BankDetailCell"
    static let EarningsCell = "EarningsCell"
    static let PaymentTypeTableViewCell = "PaymentTypeTableViewCell"
    static let CardView = "CardView"
    static let MyQRCodeViewController = "MyQRCodeViewController"
    static let QRCodeScanViewController = "QRCodeScanViewController"
    static let PopViewController = "PopViewController"

    //MARK: - Storyboard Id
    static let InviteController = "InviteViewController"
    static let MyAccountController = "MyAccountController"
    static let SupportController = "SupportController"
    static let MyProfileController = "MyProfileController"
    static let ManageAddressController = "ManageAddressController"
    static let TransactionTableViewCell = "TransactionTableViewCell"
    static let TransactionViewController = "TransactionViewController"
    static let PaymentViewController = "PaymentViewController"
    static let ChangePasswordController = "ChangePasswordController"
    static let ManageServiceController = "ManageServiceController"
    static let ManageDocumentController = "ManageDocumentController"
    static let DetailDocumentController = "DetailDocumentController"
    static let SetupVehicleController = "SetupVehicleController"
    static let AddVehicleController = "AddVehicleController"
    static let LanguageController = "LanguageController"
    static let SetupServiceController = "SetupServiceController"
    static let SubCategoryController = "SubCategoryController"
    static let AddAmountServiceController = "AddAmountServiceController"
    static let AddCardViewController = "AddCardViewController"
    static let BankDetailController = "BankDetailController"
    static let EarningsController = "EarningsController"
    static let ShowImageViewController = "ShowImageViewController"
    static let PaymentSelectViewController = "PaymentSelectViewController"
    static let payStackView = "PayStackView"
    
    //MARK: - ImageNames
    static let profileImage = "profile"
    static let location = "ic_location"
    static let paymentImage = "ic_payment"
    static let referFriend = "ic_gift_card"
    static let privacyPolicyImage = "ic_privacy_policy"
    static let supportImage = "ic_support"
    static let web = "ic_web"
    static let phone = "ic_phone"
    static let mailImage = "ic_mail"
    static let transactionImage = "ic_tansaction"
    static let Logout = "ic_logout"
    static let manageDocumentImage = "ic_manage_document"
    static let languageImage = "ic_language"
    static let circleFullImage = "ic_circle_full"
    static let circleImage = "ic_circle"
    static let check = "ic_check"
    static let error = "ErrorIcon"
    static let rightArrow = "ic_rightArrow"
    static let manageServiceImage = "ic_manage_services"
    static let deliveryMan = "ic_delivery_man"
    static let repairingService = "ic_repairing_service"
    static let scooter = "ic_scooter"
    static let file = "ic_file"
    static let dropDown = "ic_drop_down_arrow"
    static let CalendarImage = "ic_calendar"
    static let noDocument = "ic_no_document"
    static let noService = "ic_no_Service"
    static let icProfileImage = "ic_profile"
    static let cancelImage = "ic_close_cross"
    static let deleteImage = "ic_delete"
    static let earningsImage = "ic_earnings"
    static let bankicon = "ic_bank_building"
    static let pdfImage = "ic_pdf"
    static let walletSmall = "walletSmall"
    static let eyeImage = "eye"
    static let icnScan = "icnScan"
    static let ic_question = "question"
    static let ic_qrcode = "ic_qrcode"
    
    //MARK: - Paramert
    static let oldpassword = "old_password"
    static let passwordconfirmation = "password_confirmation"
    static let password = "password"
    static let PAccountType = "account_type"
    static let PUsername = "username"
    static let PEmail = "email"
    static let PMobile = "mobile"
    static let PCountryCode = "country_code"
    static let PSaltKeyValue = "MQ=="
    static let PPassword = "password"
    static let PConfirmPassword = "password_confirmation"
    static let POtp = "otp"
    static let PVehicleId = "vehicle_id"
    static let PVehicleYear = "vehicle_year"
    static let PVehicleMake = "vehicle_make"
    static let PVehicleModel = "vehicle_model"
    static let PVehicleNo = "vehicle_no"
    static let PVehcileColor = "vehicle_color"
    static let PAdminServiceId = "admin_service"
    static let PCategoryId = "category_id"
    static let PSubCategoryId = "sub_category_id"
    static let PServiceId = "admin_service"
    static let PBaseFare = "base_fare"
    static let PPerMiles = "per_miles"
    static let PPerMins = "per_mins"
    static let PPicture = "picture"
    static let PPicture1 = "picture1"
    static let PVehicleImage = "vechile_image"
    static let PType = "type"
    static let PExpiry = "expires_at"
    static let PDcoumentId = "document_id"
    static let PFile0 = "file[0]"
    static let PFile1 = "file[1]"
    static let PServiceCategoryId = "service_category_id"
    static let PServiceSubCategoryId = "service_subcategory_id"
    static let PLanguage = "language"
    static let PStripeToken = "stripe_token"
    static let PCardId = "card_id"
    static let PUsertype = "user_type"
    static let PpaymentMode = "payment_mode"
    static let PAmount = "amount"
    static let PLimit = "limit"
    static let POffset = "offset"
    static let PId = "id"
    static let PBankFormId = "bankform_id"
    static let PKeyValue = "keyvalue"
    static let Pchild_seat = "child_seat"
    static let Pwheel_chair = "wheel_chair"
}

enum ServiceType: String {
    
    case transport = "TRANSPORT"
    case order = "ORDER"
    case service = "SERVICE"
    case category = "CATEGORY"
    case subCategory = "SUBCATEGORY"
    case document = "DOCUMENT"
    case delivery = "DELIVERY"
}

enum userType: String {
    
    case user = "user"
    case Provider = "provider"
}

enum earningType: String {
    
    case today = "today"
    case week = "week"
    case month = "month"
}

enum banktypKeyboardeMode: String {
    
    case varChar = "VARCHAR"
    case int = "INT"
}

enum FareTypeEntity: String {
    case hourly = "HOURLY"
    case fixed = "FIXED"
    case distanceTime = "DISTANCETIME"
}

